"""S8 — classification hardening: size cap + generated/vendor path rules.

Measured on this machine: 34 files / 162.5 MiB of generated Figma-export JSON
(one file 125 MiB) were 47% of a project's apparent indexable bytes, and `.json`
is a legit config extension. A vendored `pdfjs/build/pdf.worker.js` sat inside
a framework layer. An extension allowlist alone is provably insufficient — a
per-file size policy and generated/vendor path rules are required.

Plan: docs/planning/RAG_V3_LOCAL_DEV_IMPLEMENTATION_PLAN.md  (S8 -> G8)
"""

from ragtools.source_class import (
    DEFAULT_MAX_FILE_BYTES,
    GENERATED,
    OWNED,
    classify_source_class,
)


def test_extraction_raw_dir_is_generated():
    assert (
        classify_source_class("figma-extraction/raw/web_canvas.json") == GENERATED
    )


def test_static_lib_is_generated():
    assert (
        classify_source_class("web/static/lib/pdfjs/build/pdf.worker.js")
        == GENERATED
    )


def test_oversized_file_is_generated():
    # A 125 MB JSON is machine-generated by definition.
    assert (
        classify_source_class("app/data.json", size_bytes=125 * 1024 * 1024)
        == GENERATED
    )


def test_normal_file_without_size_is_owned():
    # No size passed => size policy is not applied; behaviour unchanged.
    assert classify_source_class("app/models.py") == OWNED


def test_normal_small_file_is_owned():
    assert classify_source_class("app/models.py", size_bytes=2000) == OWNED


def test_default_cap_is_sane():
    # A couple MB, not gigabytes: hand-written source/config is well under it.
    assert 512 * 1024 <= DEFAULT_MAX_FILE_BYTES <= 8 * 1024 * 1024


def test_size_cap_is_configurable():
    assert (
        classify_source_class(
            "app/models.py", size_bytes=3000, max_bytes=1024
        )
        == GENERATED
    )
