"""Windows Startup-folder registration for the system-tray icon.

Sibling of startup.py — same technique (a VBS launcher placed in the
user's Startup folder) so the tray auto-starts at login with no admin
elevation and no Task Scheduler involvement.

macOS / Linux are intentionally unsupported for now; ``rag tray install``
on those platforms refuses and prints guidance.
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

from ragtools.config import Settings

logger = logging.getLogger("ragtools.service")

TRAY_STARTUP_FILENAME = "RAGTools-Tray.vbs"


def _check_windows() -> bool:
    if sys.platform != "win32":
        logger.info("Tray startup: skipped (platform=%s is not Windows)", sys.platform)
        return False
    return True


def _startup_folder() -> Path:
    appdata = os.environ.get("APPDATA", "")
    if not appdata:
        raise RuntimeError("APPDATA environment variable not set")
    return Path(appdata) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"


def _startup_script_path() -> Path:
    return _startup_folder() / TRAY_STARTUP_FILENAME


def _build_tray_script(settings: Settings) -> str:
    """VBS that silently launches ``rag tray``.

    Uses ``shell.Run cmd, 0, False`` — the 0 hides the console window so
    the tray doesn't flash an empty terminal on login; False returns
    immediately instead of waiting for the tray to exit.
    """
    from ragtools.config import is_packaged

    if is_packaged():
        exe = sys.executable
        args = "tray"
    else:
        # In source mode, use the current venv's Python + module form.
        exe = sys.executable
        args = "-m ragtools.cli tray"

    # VBS string quoting: "" inside a literal = one embedded double-quote.
    # shell.Run takes a single command string.
    vbs_cmd = f'"""{exe}"" {args}"'

    return f"""' RAGTools Tray Auto-Start
' Silently launches the RAG Tools system-tray icon on login.
' Generated by ``rag tray install``.

Dim shell
Set shell = CreateObject("WScript.Shell")
shell.Run {vbs_cmd}, 0, False
"""


def install_tray_task(settings: Settings) -> bool:
    """Place the tray launcher VBS in the user's Startup folder.

    Returns True on success, False on platform guard. Raises RuntimeError
    for filesystem problems so callers can report them precisely.
    """
    if not _check_windows():
        return False

    startup_dir = _startup_folder()
    if not startup_dir.exists():
        raise RuntimeError(f"Startup folder not found: {startup_dir}")

    script_path = _startup_script_path()
    content = _build_tray_script(settings)
    logger.info("Installing tray autostart script: %s", script_path)
    script_path.write_text(content, encoding="utf-8")
    return True


def uninstall_tray_task() -> bool:
    """Remove the tray launcher VBS. Returns True whether or not it existed."""
    if not _check_windows():
        return True
    script_path = _startup_script_path()
    if script_path.exists():
        script_path.unlink()
        logger.info("Tray autostart script removed")
    return True


def is_tray_task_installed() -> bool:
    if sys.platform != "win32":
        return False
    return _startup_script_path().exists()
